from collections.abc import Callable

from stem_agent.llm import call_text_model
from stem_agent.qa_agent import module_path_from_file, _clean_test_code
from stem_agent.schemas import PipelineSpec, StageType
from stem_agent.tools import read_text, write_text


class DynamicPipelineAgent:
    """
    Executes a pipeline generated by the stem agent.

    The agent itself has minimal domain knowledge. Its structure comes from
    PipelineSpec: prompt stages call an LLM, tool stages run Python functions.

    For the QA benchmark interface, generate_tests adds a final safety layer:
    if the pipeline output is not valid pytest code, it asks the model once
    more for valid pytest code using the original source.
    """

    name = "dynamic_pipeline_agent"

    def __init__(self, spec: PipelineSpec):
        self.spec = spec
        self._compiled_tools = self._compile_tools()

    def _compile_tools(self) -> dict[str, Callable[[str], str]]:
        tools = {}

        for stage in self.spec.stages:
            if stage.stage_type != StageType.tool or not stage.code:
                continue

            try:
                compile(stage.code, f"<pipeline_tool:{stage.name}>", "exec")
                namespace = {}
                exec(stage.code, namespace)

                fn = namespace.get("run")
                if not callable(fn):
                    raise ValueError("tool code must define callable run(input: str) -> str")

                tools[stage.name] = fn

            except Exception as exc:
                tools[stage.name] = self._failed_tool(stage.name, exc)

        return tools

    def _failed_tool(self, name: str, exc: Exception) -> Callable[[str], str]:
        def run(input_text: str) -> str:
            return f"[tool {name} failed: {exc}]\n\n{input_text}"

        return run

    def run(self, input_text: str) -> str:
        current = input_text

        for stage in self.spec.stages:
            if stage.stage_type == StageType.tool:
                fn = self._compiled_tools.get(stage.name)
                if fn is not None:
                    current = fn(current)

            elif stage.stage_type == StageType.prompt:
                current = call_text_model(stage.instruction, current)

        return current

    def generate_tests(self, problem_file: str, output_file: str) -> str:
        code = read_text(problem_file)
        module_path = module_path_from_file(problem_file)
        function_name = _extract_function_name(code)

        input_text = f"""Module import path:
{module_path}

Target function:
{function_name}

Source:
{code}

Final output must be valid pytest code.
Import using: from {module_path} import {function_name}
"""

        result = self.run(input_text)
        cleaned = _clean_test_code(result)

        if not _looks_like_valid_pytest(cleaned):
            cleaned = self._fallback_generate_pytest(
                code=code,
                module_path=module_path,
                function_name=function_name,
            )

        write_text(output_file, cleaned)
        return output_file

    def _fallback_generate_pytest(
        self,
        code: str,
        module_path: str,
        function_name: str,
    ) -> str:
        system_prompt = """
You are a Python QA agent.
Generate only valid pytest code.
Do not include markdown.
Do not explain anything.
The tests should target behavior described by the function code and docstring.
Prefer edge cases, side effects, ordering/stability, exception behavior, and boundary conditions.
"""

        user_prompt = f"""
Import using:
from {module_path} import {function_name}

Function code:
{code}

Write 2 to 5 valid pytest tests for this function.
Return only Python code.
"""

        raw = call_text_model(system_prompt, user_prompt)
        cleaned = _clean_test_code(raw)

        if _looks_like_valid_pytest(cleaned):
            return cleaned

        # Last-resort valid smoke test. This prevents invalid output from
        # corrupting the artifact, while the evaluator will correctly score it
        # as weak if it does not expose a bug.
        return f"""from {module_path} import {function_name}


def test_smoke():
    assert {function_name} is not None
"""


def _extract_function_name(code: str) -> str:
    for line in code.splitlines():
        line = line.strip()
        if line.startswith("def "):
            return line.split("def ")[1].split("(")[0]
    raise ValueError("No function definition found.")


def _looks_like_valid_pytest(code: str) -> bool:
    if "def test_" not in code:
        return False

    try:
        compile(code, "<pipeline-output>", "exec")
    except SyntaxError:
        return False

    return True
